### ISSUE TITLE
Configure input validation

### ISSUE THREAD

**Issue by shadanan** [shadanan/cipherly#36]
There exists some client side validation on some fields. It shows up like this:
<img width="677" alt="image" src="https://github.com/shadanan/cipherly/assets/361429/63be7048-e33a-4e4d-b78f-73c76e354964">

I would like much more fine grained validation to be available. I want to be able to call a function, and if it returns an error, we can display that error in the validation pop up.

**Comment by zianwar** [comment]
Client side validation can be extended with more custom logic like this:
```typescript
import { z } from "zod";
 
export const formSchema = z.object({
  username: z.string().min(2).max(50),
});
``` 
But I'm assuming we want backend side validation here. 

So, I've looked into these solutions:
1. https://kit.svelte.dev/docs/form-actions
2. https://www.shadcn-svelte.com/docs/components/form

And unfortunately none of them can work with a custom backend (Rocket), their rely on SvelteKit in non-SPA mode. So I'm left to wonder that we should just implement our custom solution.

I have yet to think about how we might accomplish that.

**Comment by zianwar** [comment]
@shadanan do we want to have field specific error messages or one global error message?

So an example 400 response from the server would look like:

1. One error message that represents the form validation status
```json
{
 "error": "Invalid values: password too short and missing cipherText"
}
```

2. Field specific validation along with a generic form validation.
```json
{
 "error": "Invalid values",
 "fields": [
   { "name": "cipherText", "message": "Invalid value" },
   { "name": "password", "message": "Password too short" }
 ]
}
```

**Comment by shadanan** [comment]
Let's limit the scope of this to client side validation. The server will never "validate" any fields. A request to decrypt will either succeed or fail. And in all cases, failure will be, Unauthorized or Internal Server Error.

Client side, however, we can help the user do good things, like:
- Ensure the payload decodes successfully
- Ensure the payload is for the correct version of Cipherly (staging / prod / dev)
- Ensure the expected fields in the payload are there
- Ensure email addresses are correctly formatted
- Ensure the secret is not empty
